# Generated by Django 3.2 on 2021-05-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTest',
        ),
        migrations.DeleteModel(
            name='test123',
        ),
    ]
