# Generated by Django 3.2 on 2021-05-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modeltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='language',
            field=models.TextField(default='Bez języka.', verbose_name='Język'),
        ),
    ]
