# Generated by Django 3.2 on 2021-05-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modeltest_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTest',
        ),
    ]
