# Generated by Django 3.1.1 on 2021-04-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_delete_bibliography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('co_authors', models.CharField(max_length=256)),
                ('editor', models.CharField(max_length=256)),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('original_edition', models.TextField()),
                ('series', models.TextField()),
                ('publication_date', models.TextField()),
                ('publication', models.TextField()),
                ('publication_place', models.TextField()),
                ('publisher', models.TextField()),
                ('source', models.TextField()),
                ('number', models.TextField()),
                ('notebook', models.TextField()),
                ('pages', models.TextField()),
                ('language', models.TextField()),
                ('isbn_or_issn_number', models.TextField()),
                ('doi_number', models.TextField()),
                ('link', models.URLField()),
                ('keywords_and_content', models.TextField()),
                ('comments', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
