# Generated by Django 3.1.1 on 2021-04-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bibliography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliography',
            name='author',
        ),
    ]
