# Generated by Django 3.1.1 on 2021-04-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bibliography_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bibliography',
        ),
    ]
