# Generated by Django 3.2 on 2021-04-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
