# Generated by Django 3.2 on 2021-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel_To_Tb_Test_2018',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_test_2018',
                'abstract': False,
            },
        ),
    ]
