# Generated by Django 3.2 on 2021-04-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210428_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateModel_To_Tb_Bibligoraphy_1',
        ),
    ]
