# Generated by Django 3.2.8 on 2021-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210823_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadbinfo',
            name='description',
            field=models.CharField(default='description database', max_length=2000),
        ),
        migrations.AlterField(
            model_name='metadbinfo',
            name='author',
            field=models.CharField(default='author database', max_length=50),
        ),
        migrations.AlterField(
            model_name='metadbinfo',
            name='db_name',
            field=models.CharField(default='name of database', max_length=200),
        ),
        migrations.AlterField(
            model_name='metadbinfo',
            name='real_db_name',
            field=models.CharField(default='real_name database', max_length=200),
        ),
    ]
