# Generated by Django 3.2.8 on 2021-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211130_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadbinfo',
            name='author',
            field=models.CharField(default='author databasee', max_length=50),
        ),
    ]
