# Generated by Django 3.2 on 2021-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_delete_templatemodel_to_tb_bibligoraphy_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_bibliography_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'table_bibliography_test',
                'abstract': False,
            },
        ),
    ]
