# Generated by Django 3.2.8 on 2021-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_metadbinfo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadbinfo',
            name='author',
            field=models.CharField(default='author database', max_length=50),
        ),
        migrations.AlterField(
            model_name='metadbinfo',
            name='description',
            field=models.TextField(default='description database'),
        ),
    ]
