# Generated by Django 3.2 on 2021-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_table_bibliography_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_bibliography_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'table_bibliography_1',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='table_bibliography_test',
        ),
    ]
