# Generated by Django 3.2 on 2021-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210428_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='bibliography_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bibliography_test',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bibliography_test_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bibliography_test_1',
                'abstract': False,
            },
        ),
    ]
