# Generated by Django 3.2 on 2021-04-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bibliography_test_bibliography_test_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_bibliography_1',
        ),
    ]
