# Generated by Django 3.2 on 2021-04-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210429_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography_db_1',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='bibliography_db_2',
            options={'verbose_name_plural': ''},
        ),
    ]
