# Generated by Django 3.2 on 2021-04-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210429_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography_db_1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bibliography_db_2',
            options={},
        ),
    ]
