# Generated by Django 3.2 on 2021-04-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210429_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bibliography_db_1',
        ),
        migrations.DeleteModel(
            name='bibliography_db_2',
        ),
    ]
