# Generated by Django 3.2 on 2021-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0020_auto_20210429_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='bibliography_db_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bibliography_db_1',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bibliography_db_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bibliography_db_2',
                'abstract': False,
            },
        ),
    ]
