# Generated by Django 3.2 on 2021-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210429_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='co_authors',
            field=models.CharField(default='Bez współtwórcy.', max_length=256),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='comments',
            field=models.TextField(default='Bez komentarzy.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='doi_number',
            field=models.TextField(default='Bez numeru DOI.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='editor',
            field=models.CharField(default='Bez redaktora.', max_length=256),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='isbn_or_issn_number',
            field=models.TextField(default='Bez numeru ISBN/ISSN.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='keywords_and_content',
            field=models.TextField(default='Bez słów kluczowych/zawratości.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='language',
            field=models.TextField(default='Bez języka.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='notebook',
            field=models.TextField(default='Bez zeszytu.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='number',
            field=models.TextField(default='Bez numeru.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='original_edition',
            field=models.TextField(default='Bez wydania oryginalnego.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='pages',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='publication',
            field=models.TextField(default='Bez wydania.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='publication_date',
            field=models.SmallIntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='publication_place',
            field=models.TextField(default='Bez miejsca wydania.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='publisher',
            field=models.TextField(default='Bez wydawcy.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='series',
            field=models.TextField(default='Bez numeru serii.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='source',
            field=models.TextField(default='Bez źródła.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='subtitle',
            field=models.TextField(default='Bez podtytułu.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_1',
            name='title',
            field=models.TextField(default='Brak Tytułu.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='co_authors',
            field=models.CharField(default='Bez współtwórcy.', max_length=256),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='comments',
            field=models.TextField(default='Bez komentarzy.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='doi_number',
            field=models.TextField(default='Bez numeru DOI.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='editor',
            field=models.CharField(default='Bez redaktora.', max_length=256),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='isbn_or_issn_number',
            field=models.TextField(default='Bez numeru ISBN/ISSN.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='keywords_and_content',
            field=models.TextField(default='Bez słów kluczowych/zawratości.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='language',
            field=models.TextField(default='Bez języka.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='notebook',
            field=models.TextField(default='Bez zeszytu.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='number',
            field=models.TextField(default='Bez numeru.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='original_edition',
            field=models.TextField(default='Bez wydania oryginalnego.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='pages',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='publication',
            field=models.TextField(default='Bez wydania.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='publication_date',
            field=models.SmallIntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='publication_place',
            field=models.TextField(default='Bez miejsca wydania.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='publisher',
            field=models.TextField(default='Bez wydawcy.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='series',
            field=models.TextField(default='Bez numeru serii.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='source',
            field=models.TextField(default='Bez źródła.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='subtitle',
            field=models.TextField(default='Bez podtytułu.'),
        ),
        migrations.AlterField(
            model_name='bibliography_db_2',
            name='title',
            field=models.TextField(default='Brak Tytułu.'),
        ),
    ]
