# Generated by Django 3.2 on 2021-04-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210429_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nabiałczyk_bibliografia_o_iinib_uwr',
            table='nabiałczyk_bibliografia_o_iinib_UWr',
        ),
    ]
