# Generated by Django 3.2 on 2021-04-29 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_auto_20210429_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_authors', models.CharField(default='Bez współtwórcy.', max_length=256)),
                ('editor', models.CharField(default='Bez redaktora.', max_length=256)),
                ('title', models.TextField(default='Brak Tytułu.')),
                ('subtitle', models.TextField(default='Bez podtytułu.')),
                ('original_edition', models.TextField(default='Bez wydania oryginalnego.')),
                ('series', models.TextField(default='Bez numeru serii.')),
                ('publication_date', models.SmallIntegerField(default=1900)),
                ('publication', models.TextField(default='Bez wydania.')),
                ('publication_place', models.TextField(default='Bez miejsca wydania.')),
                ('publisher', models.TextField(default='Bez wydawcy.')),
                ('source', models.TextField(default='Bez źródła.')),
                ('number', models.TextField(default='Bez numeru.')),
                ('notebook', models.TextField(default='Bez zeszytu.')),
                ('pages', models.SmallIntegerField(default=0)),
                ('language', models.TextField(default='Bez języka.')),
                ('isbn_or_issn_number', models.TextField(default='Bez numeru ISBN/ISSN.')),
                ('doi_number', models.TextField(default='Bez numeru DOI.')),
                ('link', models.URLField()),
                ('keywords_and_content', models.TextField(default='Bez słów kluczowych/zawratości.')),
                ('comments', models.TextField(default='Bez komentarzy.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test1',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
