# Generated by Django 3.0.7 on 2021-05-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_testowa_bibliografia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testowa_bibliografia',
        ),
    ]
