# Generated by Django 3.0.7 on 2021-05-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_delete_testowa_bibliografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='augustyn_corpus1_the_global_book_publishing_market',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='augustyn_global_book_publishing_2001_2018',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='bernacki_miedzywojenna_fantastyka',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='cislo_irlandia',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='hojka_slowniki_dla_dzieci_1989_2015',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='lubocki_bibliografia_elementarzy_1945_2012_podmiotowa',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='lubocki_bibliografia_elementarzy_1945_2012_przedmiotowa',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='lubocki_bibliografia_podmiotowa_stefanii_grodzieńskiej',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='lubocki_bibliografia_przedmiotowa_stefanii_grodzieńskiej',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
        migrations.AddField(
            model_name='nabialczyk_bibliografia_o_iinib_uwr',
            name='book_author',
            field=models.CharField(default='Bez autora', max_length=512),
        ),
    ]
