# Generated by Django 3.0.7 on 2021-05-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210503_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augustyn_corpus1_the_global_book_publishing_market',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='augustyn_global_book_publishing_2001_2018',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='bernacki_miedzywojenna_fantastyka',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='cislo_irlandia',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='hojka_slowniki_dla_dzieci_1989_2015',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='lubocki_bibliografia_elementarzy_1945_2012_podmiotowa',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='lubocki_bibliografia_elementarzy_1945_2012_przedmiotowa',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='lubocki_bibliografia_podmiotowa_stefanii_grodzieńskiej',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='lubocki_bibliografia_przedmiotowa_stefanii_grodzieńskiej',
            name='pages',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='nabialczyk_bibliografia_o_iinib_uwr',
            name='pages',
            field=models.TextField(default='0'),
        ),
    ]
