# Generated by Django 3.2 on 2021-05-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210429_1750'),
        ('api', '0031_auto_20210503_1239'),
    ]

    operations = [
    ]
